### PR TITLE
Add selectable editor themes

### PR DESCRIPTION
**Pull request by keithlayne**
This adds a new 'Theme' dropdown menu to the playground. Themes include:

- light (current playground theme)
- dark
- dark with high contrast

On load all themes are registered, and them localStorage is checked for
any saved theme, defaulting to 'light'.  Updates store the last selected
theme in localStorage.

Related: microsoft/TypeScript-Website#90

### CODE REVIEW

**Comment by keithlayne** [comment]
I added a checkmark as an indicator in the dropdown menu.  It doesn't look good IMO.  Let me know if I should just get rid of it.  I was thinking there was something like that in bootstrap 3, but didn't see it.  I guess it could be like a dropdown select if you want.

Also, seems a little janky on load when you're not using the light theme, but that's probably worse for me right now because I have a pretty high-latency connection right now.

Let me know if I should deploy this using gh-pages so you can see it in action without having to check this out.

**Comment by keithlayne** [comment]
TODO:  Add the 'crockford' theme.  That's black on white with no syntax highlighting, because syntax highlighting is for kindergardeners.

# 🚎

**Comment by orta** [comment]
Hah at the Crockford theme, blows my mind that 



Alright, this is ready to go.

**Comment by orta** [comment]
It doesn't blink on reload when you're in dark too now

**Comment by keithlayne** [comment]
Yeah so I had to disable format on save and didn't stage those trailing whitespace changes.  Whole thing could use a trip through prettier so my editor doesn't try to rewrite all the files.

**Comment by orta** [comment]
Yeah, I have to have my formatters disabled because of the examples which need custom formatting

**Comment by keithlayne** [comment]
Well, there's already a `.prettierignore`, so add them to that maybe?

Anyway, thanks for making this happen, you have increased the happiness in the world.

**Pull request merged**
