### PR TITLE
Feature: Add export buttons options

### PR DESCRIPTION
**Pull request by br1anchen**
Based on #29 , feel free to give feedback.

Current added export options:
- Report GitHub issue on TypeScript
- Copy as Markdown (currently only copy the same Github issue markdown to clipboard, like [prettier playground)](https://prettier.io/playground/)
- Open in CodeSandbox
- Open in StackBlitz (implemented in #29 )

### CODE REVIEW

**Comment by orta** [comment]
This is a really great step forwards @br1anchen ! Thanks

I'll take a look at wrapping some extra stuff up: because a lot of this work is around system level integrations like redirect or copying something there is additional work needed to make sure that it doesn't trigger popup blockers or the system guards for the pasteboard.

**Comment by orta** [comment]
great work on `getValidCompilerOptions`

**Comment by orta** [comment]
OK, let's get this working on staging and deploy if it feels good - thanks @br1anchen

**Comment by br1anchen** [comment]
@orta Great work 👍 Glad to help :)

**Pull request merged**
