### PR TITLE
[WIP] Export to ... support

### PR DESCRIPTION
**Pull request by orta**
Currently works with StackBlitz

- I have some notes in https://github.com/microsoft/TypeScript-Website/issues/46 about the code sandbox API
- I'd expect the link to make an issue to work like the [prettier playground](https://prettier.io/playground/) see bottom right
- Not sure wha to expect from copy to markdown, maybe a popover with a textarea previewing it and selected for you to copy

**note to work on this**, you need to get a copy of the website https://github.com/microsoft/TypeScript-website#configure-your-build-environment then change the submodule in `src/play` to be these commits.

Screen Shot 2019-10-25 at 12 12 57 PM

Screen Shot 2019-10-25 at 12 13 13 PM

### CODE REVIEW

**Comment by AnyhowStep** [comment]
"Copy as .d.ts" as a temporary hack to support emitting .d.ts? =x

**Comment by orta** [comment]
> d.ts

I threw an hour at getting the d.ts file sometime last week and I feel like there's something in Monaco-typescript which made that hard. Will look again sometime after this mini-conference season is over for me

--

Also, we can support export to ts-ast-viewer because of https://github.com/dsherret/ts-ast-viewer/pull/59

**Comment by CompuIves** [comment]
This is so cool!

For anyone who wants to take a stab at creating the CodeSandbox implementation, the API has been simplified a bit for creating a sandbox (I kind of forgot that we had this, so I'll add it to the docs). Nowadays you can do a POST request without any param parsing, and you can get json back if you want to. Here's an example:

https://codesandbox.io/s/nostalgic-brahmagupta-3f7e8

This is the gist of it:

```js
  const files = {
    "package.json": {
      content: {}
    },
    "index.ts": {
      content: "let a = 'b';"
    }
  };

  fetch("https://codesandbox.io/api/v1/sandboxes/define?json=1", {
    method: "POST",
    body: JSON.stringify({ files }),
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json"
    }
  })
```

**Comment by wuweiweiwu** [comment]
I would love to pick this up! 🎉

**Comment by br1anchen** [comment]
@orta @CompuIves I made PR based on this WIP PR, please feel free to comment/iterate on it

**Comment by orta** [comment]
Deprecated by #30  which just needs a modal to show a textarea for the copy options in the export (to ensure that copy works reliably)

**Pull request closed without merging**
